apiVersion: v1
kind: Service
metadata:
  name: s3-service
  namespace: s3
spec:
  type: NodePort
  selector:
    app: s3-application
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30728
      
      
 